trigger:
- main
- feature/*
pool: SelfHostedpool
parameters:
- name: ScanningMandatory
  displayName: tfsecScanning
  type: string
  default: true
  values:
   - true
   - false
jobs:
  - job: TerraformInit
    displayName: This job will run validatd and init
    
    steps:
     - task: TerraformTask@5
       inputs:
         provider: 'azurerm'
         command: 'init'
         workingDirectory: '$(System.DefaultWorkingDirectory)/TODOAPP_INFRA'
         backendServiceArm: 'SecretSP'
         backendAzureRmOverrideSubscriptionID: '81cc1915-8d88-419e-8fa3-0178811761bd'
         backendAzureRmResourceGroupName: 'HAR-RG'
         backendAzureRmStorageAccountName: 'harpracticestorage'
         backendAzureRmContainerName: 'statecontainer'
         backendAzureRmKey: 'terraform.tfstate'
     - task: TerraformTask@5
       inputs:
         provider: 'azurerm'
         command: 'validate'
         workingDirectory: '$(System.DefaultWorkingDirectory)/TODOAPP_INFRA'
  - job: ScanningJob
    condition: eq(${{parameters.ScanningMandatory}},'true')
    displayName: Scanning Wala Job
    steps:
    - task: tfsec@1
      inputs:
        version: 'v1.26.0'
        dir: '$(System.DefaultWorkingDirectory)/TODOAPP_INFRA'
  - job: TerraformInitPlan
    steps:
    - task: TerraformTask@5
      inputs:
        provider: 'azurerm'
        command: 'init'
        workingDirectory: '$(System.DefaultWorkingDirectory)/TODOAPP_INFRA'
        backendServiceArm: 'SecretSP'
        backendAzureRmStorageAccountName: 'harpracticestorage'
        backendAzureRmContainerName: 'statecontainer'
        backendAzureRmKey: 'terraform.tfstate'
    - task: TerraformTask@5
      inputs:
         provider: 'azurerm'
         command: 'plan'
         workingDirectory: '$(System.DefaultWorkingDirectory)/TODOAPP_INFRA'
         environmentServiceNameAzureRM: 'SecretSP'
         environmentAzureRmOverrideSubscriptionID: '81cc1915-8d88-419e-8fa3-0178811761bd'
  - job: ManualValidation
    displayName: Manual Validation
    pool: server
    steps:
    - task: ManualValidation@1
      inputs:
        notifyUsers: 'harveer25@gmail.com'
        approvers: 'harveer25@gmail.com'
        onTimeout: 'resume'
  - job: TerraformApply
    displayName: Terraforn Apply
    dependsOn: ManualValidation     
    steps:
    - task: TerraformTask@5
      inputs:
        provider: 'azurerm'
        command: 'apply'
        workingDirectory: '$(System.DefaultWorkingDirectory)/TODOAPP_INFRA'
        environmentServiceNameAzureRM: 'SecretSP'
        environmentAzureRmOverrideSubscriptionID: '81cc1915-8d88-419e-8fa3-0178811761bd'
