trigger:
- main
- feature/*
parameters:
- name: ScanningisMandatory
  displayName: tfsecScanning
  type: string
  values:
   - true
   - false
jobs:
  - job: TerraformInitPlanApply
    displayName: This job will run init,plan and apply
    pool: SelfHostedpool
    steps:
     - task: TerraformTask@5
       inputs:
         provider: 'azurerm'
         command: 'init'
         workingDirectory: '$(System.DefaultWorkingDirectory)/TODOAPP_INFRA'
         backendServiceArm: 'SecretSP'
         backendAzureRmOverrideSubscriptionID: '81cc1915-8d88-419e-8fa3-0178811761bd'
         backendAzureRmResourceGroupName: 'HAR-RG'
         backendAzureRmStorageAccountName: 'harpracticestorage'
         backendAzureRmContainerName: 'statecontainer'
         backendAzureRmKey: 'terraform.tfstate'
     - task: TerraformTask@5
       inputs:
         provider: 'azurerm'
         command: 'validate'
         workingDirectory: '$(System.DefaultWorkingDirectory)/TODOAPP_INFRA'
  - job: ScanningJob
    condition: eq(${{parameters.ScanningisMandatory}},'true')
    
          
         
     - task: TerraformTask@5
       inputs:
         provider: 'azurerm'
         command: 'plan'
         workingDirectory: '$(System.DefaultWorkingDirectory)/TODOAPP_INFRA'
         environmentServiceNameAzureRM: 'SecretSP'
         environmentAzureRmOverrideSubscriptionID: '81cc1915-8d88-419e-8fa3-0178811761bd'
     - task: TerraformTask@5
       inputs:
         provider: 'azurerm'
         command: 'apply'
         workingDirectory: '$(System.DefaultWorkingDirectory)/TODOAPP_INFRA'
         environmentServiceNameAzureRM: 'SecretSP'
         environmentAzureRmOverrideSubscriptionID: '81cc1915-8d88-419e-8fa3-0178811761bd'
